"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const HomeControler_1 = require("./src/controller/HomeControler");
const { indexProductPage } = require("./src/controller/ProductPageController.js");
const AdminPageController_js_1 = require("./src/controller/AdminPageController.js");
const multer = require('multer');
const { ativacaoIndex } = require("./src/controller/AtbPageController.js");
const multerConfig = require("./src/config/multerConfig");
const uploads = multer(multerConfig);
router.get("/", HomeControler_1.index);
router.get("/products/", indexProductPage);
router.get("/products/atb/index", ativacaoIndex);
router.get("/admin/", AdminPageController_js_1.indexAdmin);
router.post("/admin/create/", AdminPageController_js_1.create);
router.get("/admin/delete/:id", AdminPageController_js_1.deleteProduct);
exports.default = router;
